# Generated by Django 2.2.3 on 2020-01-19 01:41

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('average_fuel', models.IntegerField(default=0)),
                ('delegation_starting', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('delegation_ending', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('driver', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Company', 'Company'), ('Private', 'Private')], max_length=200)),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('modify_at', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('deleted_at', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoPartnerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_partner.Auto')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('modify_at', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('deleted_at', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('autos', models.ManyToManyField(through='auto_partner.AutoPartnerRelation', to='auto_partner.Auto')),
            ],
        ),
        migrations.AddField(
            model_name='autopartnerrelation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_partner.Partner'),
        ),
        migrations.AddField(
            model_name='auto',
            name='partners',
            field=models.ManyToManyField(through='auto_partner.AutoPartnerRelation', to='auto_partner.Partner'),
        ),
    ]
