# Generated by Django 2.2.3 on 2020-01-20 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='assigned_partners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=[], size=None),
        ),
        migrations.AddField(
            model_name='partner',
            name='assigned_autos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=[], size=None),
        ),
    ]
